# This is a basic workflow to help you get started with Actions

name: CI

env:
  resourceGroup: 'argocd-demo-rg'
  name: 'argocd-main-aks'
  kubernetes-version: '1.26.3'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # ClientId of the Azure Service principal created.
        # client-id: # optional
        # TenantId of the Azure Service principal created.
        # tenant-id: # optional
        # Azure subscriptionId
        # subscription-id: # optional
        # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login

    - name: Azure CLI Action
      uses: Azure/cli@v1.0.8
      with:
        # Specify the script here
        inlineScript: az aks create -g ${{ env.resourceGroup }} -n ${{ env.name }} --kubernetes-version ${{ env.kubernetesVersion }} --generate-ssh-keys
