name: Argo CD Install

env:
  resourceGroup: 'argocd-demo-rg'
  name: 'argocd-main-aks'
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'


      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ env.resourceGroup }}' 
          cluster-name: '${{ env.name }}'


      - name: Install vcluster CLI (amd64)
        run: |
          curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64"
          sudo install -c -m 0755 vcluster /usr/local/bin
          rm -f vcluster
          vcluster --version


      - name: Create values.yaml and Deploy vcluster
        run: |
          echo -e "vcluster: \n  image: rancher/k3s:v1.23.5-k3s1" > values.yaml
          helm upgrade --install my-vcluster --values values.yaml --repo https://charts.loft.sh --namespace vcluster --repository-config=''
          sleep 30s
          kubectl get pods -n vcluster
